### ISSUE TITLE
Norwegian language causes ArgumentError

### ISSUE THREAD

**Issue by weakfl** [Supmenow/fastlane-plugin-poeditor-export#4]
Somehow using Norwegian as language causes an `ArgumentError` when trying to export from POEditor. Is 'no' some kind of keyword or something? It's working with every language but 'no' and if I change the language to 'Norwegian Bokmål' on POEditor.com it works.

Heres' the error I'm getting:
```bash
[13:00:11]: Driving the lane 'ios poeditor' 🚀
[13:00:11]: -----------------------------------------------
[13:00:11]: --- Step: Switch to ios poeditor_fetch lane ---
[13:00:11]: -----------------------------------------------
[13:00:11]: Cruising over to lane 'ios poeditor_fetch' 🚖
[13:00:11]: -----------------------------
[13:00:11]: --- Step: poeditor_export ---
[13:00:11]: -----------------------------
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | ios          |
| PLATFORM_NAME    | ios          |
| LANE_NAME        | ios poeditor |
+------------------+--------------+
[13:00:12]: bad argument (expected URI object or URI string)

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | Switch to ios poeditor_fetch lane   | 0           |
| 💥   | poeditor_export                     | 1           |
+------+-------------------------------------+-------------+

[13:00:12]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

🔗 You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/uri/common.rb:716:in `URI': [!] bad argument (expected URI object or URI string) (ArgumentError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-plugin-poeditor_export-0.3.0/lib/fastlane/plugin/poeditor_export/helper/poeditor_export_helper.rb:25:in `export_for_language'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-plugin-poeditor_export-0.3.0/lib/fastlane/plugin/poeditor_export/actions/poeditor_export_action.rb:6:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:239:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:83:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:188:in `try_switch_to_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:143:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:71:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

And here are the corresponding lanes from my Fastfile:
```ruby
desc "Import translations from POEditor"
lane :poeditor do
  poeditor_fetch(lang: "da", folder: "")
  poeditor_fetch(lang: "de", folder: "")
  poeditor_fetch(lang: "el", folder: "")
  poeditor_fetch(lang: "en", folder: "")
  poeditor_fetch(lang: "es", folder: "")
  poeditor_fetch(lang: "fi", folder: "")
  poeditor_fetch(lang: "fr", folder: "")
  poeditor_fetch(lang: "hu", folder: "")
  poeditor_fetch(lang: "it", folder: "")
  poeditor_fetch(lang: "ja", folder: "")
  poeditor_fetch(lang: "ko", folder: "")
  poeditor_fetch(lang: "no", folder: "")
  poeditor_fetch(lang: "nl", folder: "")
  poeditor_fetch(lang: "pt", folder: "")
  poeditor_fetch(lang: "ru", folder: "")
  poeditor_fetch(lang: "sv", folder: "")
  poeditor_fetch(lang: "th", folder: "")
  poeditor_fetch(lang: "tr", folder: "")
  poeditor_fetch(lang: "vi", folder: "")
  poeditor_fetch(lang: "zh-cn", folder: "zh-Hans")
end

desc "Import specific language from POEditor"
private_lane :poeditor_fetch do |options|
  lang = options[:lang]
  folder = options[:folder]

  if folder == ''
    folder = lang
  end

  poeditor_export(
    api_token: "removed",
    project_id: "removed",
    export_format: 'apple_strings',
    language: lang,
    output_path: "appname/Resources/#{folder}.lproj/Localizable.strings"
  )
  poeditor_export(
    api_token: "removed",
    project_id: "removed",
    export_format: 'apple_strings',
    language: lang,
    tag: 'infoplist.strings',
    output_path: "appname/Resources/#{folder}.lproj/InfoPlist.strings"
  )
end
```

Do you have any idea what might be causing this issue?

**Comment by jcampbell05** [comment]
I'm wondering if there is something to do with that language that changes, I suspect the culprit could be this line

https://github.com/jcampbell05/fastlane-plugin-poeditor_export/blob/master/lib/fastlane/plugin/poeditor_export/helper/poeditor_export_helper.rb#L25

Maybe if you could get the JSON output for that language then It would be a big help :)

**Comment by weakfl** [comment]
Thanks for looking into it!

I've made a curl request to the POEditor API and the output looks pretty normal to me:
```json
{"response":{"status":"success","code":"200","message":"OK"},"item":"https:\/\/poeditor.com\/api\/download\/file\/2edf25fa9e18dae4cdf6104f601c29d3"}
```

I think the response you're getting on [Line 22](https://github.com/jcampbell05/fastlane-plugin-poeditor_export/blob/master/lib/fastlane/plugin/poeditor_export/helper/poeditor_export_helper.rb#L22) must already be different from what I'm getting via curl.

As mentioned, if i change the language on POEditor.com from `no` to `nb` it starts working. The terms are all the same, so it must be the language code `no` that is causing the problem.

**Comment by jcampbell05** [comment]
@weakfl  It's odd because I can't think of any reason why Ruby would hate the language code `no`, I'll try and debug this.

**Comment by AndersAppDev** [comment]
I'm getting the same error:

... ruby/2.3.0/uri/common.rb:716:in `URI': [!] bad argument (expected URI object or URI string) (ArgumentError)

... ruby-2.3.1/gems/fastlane-plugin-poeditor_export-0.3.0/lib/fastlane/plugin/poeditor_export/helper/poeditor_export_helper.rb:25:in `export_for_language'

... ruby-2.3.1/gems/fastlane-plugin-poeditor_export-0.3.0/lib/fastlane/plugin/poeditor_export/actions/poeditor_export_action.rb:6:in `run'

Did you guys @jcampbell05 @weakfl ever find a solution ?

**Comment by weakfl** [comment]
@AndersAppDev I've just changed the language on poeditor.com to `nb` (Norwegian Bokmål). Problem solved ;)
